import {
  BookOpen,
  Bot,
  Brain,
  Briefcase,
  Calendar,
  ChartArea,
  ChartBar,
  CheckCircle,
  Cloud,
  Code,
  Cpu,
  Database,
  FileText,
  GitBranch,
  Globe,
  GraduationCap,
  Network,
  Phone,
  PinIcon,
  Rocket,
  SatelliteDish,
  Scan,
  Server,
  ShoppingCart,
  Target,
  User,
  User2,
  Workflow,
  Wrench,
} from "lucide-react";

export const navigation = [
  {
    name: "Projects",
    href: "/projects",
    icon: Briefcase,
    description: "Project Clusters",
    color: "from-blue-500 to-cyan-500",
    gradient: "bg-gradient-to-r from-blue-500 to-cyan-500",
    hasDropdown: true,
  },
  {
    name: "Blog",
    href: "/blog",
    icon: FileText,
    description: "Knowledge Clouds",
    color: "from-purple-500 to-pink-500",
    gradient: "bg-gradient-to-r from-purple-500 to-pink-500",
    hasDropdown: true,
  },
  {
    name: "About",
    href: "/about",
    icon: User,
    description: "My Journey",
    color: "from-orange-500 to-red-500",
    gradient: "bg-gradient-to-r from-orange-500 to-red-500",
  },
  {
    name: "Contact",
    href: "/contact",
    icon: SatelliteDish,
    description: "Connect Pulse",
    color: "from-indigo-500 to-purple-500",
    gradient: "bg-gradient-to-r from-indigo-500 to-purple-500",
  },
];

export const quickActions = [
  {
    name: "AI Playground",
    icon: Brain,
    href: "/ai-playground",
    color: "text-purple-400",
  },
  { name: "Code Lab", icon: Code, href: "/code-lab", color: "text-blue-400" },
  {
    name: "System Scan",
    icon: Scan,
    href: "/system",
    color: "text-green-400",
  },
];
 
export const aiStats = [
  {
    number: "10+",
    label: "Completed Projects",
    icon: CheckCircle,
    description: "Full-stack applications with modern technologies",
    gradient: "from-purple-500 to-pink-500",
  },
  {
    number: "5+",
    label: "AI/ML Projects",
    icon: Brain,
    description: "Advanced AI applications and integrations",
    gradient: "from-blue-500 to-cyan-500",
  },
  {
    number: "100%",
    label: "Live Demos",
    icon: Rocket,
    description: "All projects deployed and accessible",
    gradient: "from-green-500 to-emerald-500",
  },
  {
    number: "Full-Stack",
    label: "Developer",
    icon: Target,
    description: "End-to-end development expertise",
    gradient: "from-orange-500 to-red-500",
  },
];
export const techStack = {
  "AI & ML": ["LangChain", "MCP", "OpenAI API", "Vector Databases"],
  Frontend: ["Next.js", "React", "TypeScript", "Tailwind CSS"],
  Backend: ["Node.js", "Python", "FastAPI", "Express"],
  Tools: ["Git", "Docker", "Vercel", "VS Code"],
};
 
export const aiLearningPath = [
  {
    phase: "Foundation",
    topics: ["Python Basics", "API Integration", "Async Programming"],
    icon: BookOpen,
    status: "Completed",
    progress: 100,
  },
  {
    phase: "LangChain Core",
    topics: ["Chains", "Agents", "Memory", "Prompts"],
    icon: Brain,
    status: "In Progress",
    progress: 75,
  },
  {
    phase: "MCP & Advanced",
    topics: [
      "Model Context Protocol",
      "Tool Development",
      "Agent Orchestration",
    ],
    icon: GitBranch,
    status: "Learning",
    progress: 40,
  },
  {
    phase: "Production Ready",
    topics: ["Deployment", "Monitoring", "Scalability", "Best Practices"],
    icon: Cloud,
    status: "Next Steps",
    progress: 10,
  },
];

// টেক স্ট্যাক - AI ফোকাস
//   const techStack = {
//     "AI & ML": ["LangChain", "OpenAI API", "TensorFlow.js", "Vector Databases"],
//     Frontend: ["Next.js", "React", "TypeScript", "Tailwind CSS"],
//     Backend: ["Node.js", "Python", "FastAPI", "Express", "NestJS"],
//     Database: ["PostgreSQL", "MongoDB", "Redis", "TimescaleDB"],
//     Tools: ["Git", "Docker", "Vercel", "AWS", "WebSocket"],
//   };
// All Projects Data
// export const allProjects = [
//   {
//     id: "ai-chatbot",
//     title: "AI-Powered Chatbot Platform",
//     description:
//       "Intelligent chatbot platform with natural language processing, multi-channel support, and analytics.",
//     tech: [
//       "Next.js 14",
//       "TypeScript",
//       "Python",
//       "FastAPI",
//       "OpenAI GPT-4",
//       "LangChain",
//       "Pinecone",
//       "Redis",
//     ],
//     status: "Completed",
//     github: "https://github.com/sorujmahmud/ai-chatbot",
//     demo: "https://ai-chatbot-soruj.vercel.app",
//     features: [
//       "Natural Language Processing",
//       "Multi-channel Integration",
//       "Real-time Analytics",
//       "Custom AI Training",
//     ],
//     category: "ai",
//     icon: Bot,
//     gradient: "from-purple-500/10 to-pink-500/10",
//     featured: true,
//     duration: "4 months",
//     teamSize: "3 developers",
//   },
//   {
//     id: "crypto-dashboard",
//     title: "Cryptocurrency Trading Dashboard",
//     description:
//       "Real-time cryptocurrency trading platform with portfolio tracking, analytics, and automated trading.",
//     tech: [
//       "React",
//       "TypeScript",
//       "Node.js",
//       "WebSocket",
//       "PostgreSQL",
//       "Redis",
//       "D3.js",
//       "Chart.js",
//     ],
//     status: "Completed",
//     github: "https://github.com/sorujmahmud/crypto-dashboard",
//     demo: "https://crypto-soruj.vercel.app",
//     features: [
//       "Real-time Market Data",
//       "Portfolio Tracking",
//       "Automated Trading",
//       "Technical Analysis",
//     ],
//     category: "fullstack",
//     icon: ChartBar,
//     gradient: "from-blue-500/10 to-cyan-500/10",
//     featured: true,
//     duration: "5 months",
//     teamSize: "2 developers",
//   },
//   {
//     id: "fitness-tracker",
//     title: "AI Fitness Tracker & Coach",
//     description:
//       "Intelligent fitness tracking application with AI-powered workout plans, progress analytics, and virtual coaching.",
//     tech: [
//       "React Native",
//       "TypeScript",
//       "Node.js",
//       "TensorFlow.js",
//       "MongoDB",
//       "AWS S3",
//     ],
//     status: "Completed",
//     github: "https://github.com/sorujmahmud/fitness-tracker",
//     demo: "https://fitness-soruj.vercel.app",
//     features: [
//       "AI Workout Plans",
//       "Progress Tracking",
//       "Nutrition Tracking",
//       "Virtual Coach",
//     ],
//     category: "mobile",
//     icon: User2,
//     gradient: "from-green-500/10 to-emerald-500/10",
//     featured: true,
//     duration: "6 months",
//     teamSize: "4 developers",
//   },
//   {
//     id: "learning-platform",
//     title: "Interactive Learning Management System",
//     description:
//       "Modern LMS with video courses, interactive quizzes, progress tracking, and AI-powered recommendations.",
//     tech: [
//       "Next.js 14",
//       "TypeScript",
//       "NestJS",
//       "PostgreSQL",
//       "Redis",
//       "AWS S3",
//       "WebRTC",
//     ],
//     status: "Completed",
//     github: "https://github.com/sorujmahmud/learning-platform",
//     demo: "https://learn-soruj.vercel.app",
//     features: [
//       "Interactive Courses",
//       "Live Coding",
//       "AI Recommendations",
//       "Progress Tracking",
//     ],
//     category: "fullstack",
//     icon: GraduationCap,
//     gradient: "from-indigo-500/10 to-purple-500/10",
//     featured: true,
//     duration: "7 months",
//     teamSize: "5 developers",
//   },
//   {
//     id: "social-network",
//     title: "Developer Social Network",
//     description:
//       "Professional social network for developers with code sharing, collaboration tools, and job matching.",
//     tech: [
//       "React",
//       "TypeScript",
//       "Node.js",
//       "GraphQL",
//       "PostgreSQL",
//       "WebSocket",
//       "Elasticsearch",
//     ],
//     status: "In Progress",
//     github: "https://github.com/sorujmahmud/dev-network",
//     demo: "https://dev-network-soruj.vercel.app",
//     features: [
//       "Code Sharing",
//       "Real-time Collaboration",
//       "Job Matching",
//       "Technical Discussions",
//     ],
//     category: "fullstack",
//     icon: Network,
//     gradient: "from-orange-500/10 to-red-500/10",
//     featured: false,
//     duration: "8 months",
//     teamSize: "6 developers",
//   },
//   {
//     id: "iot-dashboard",
//     title: "IoT Device Management Dashboard",
//     description:
//       "Enterprise IoT platform for device management, real-time monitoring, and data analytics.",
//     tech: [
//       "React",
//       "TypeScript",
//       "Node.js",
//       "MQTT",
//       "PostgreSQL",
//       "TimescaleDB",
//       "Redis",
//       "Docker",
//     ],
//     status: "Completed",
//     github: "https://github.com/sorujmahmud/iot-dashboard",
//     demo: "https://iot-soruj.vercel.app",
//     features: [
//       "Real-time Monitoring",
//       "Device Management",
//       "Data Analytics",
//       "Predictive Maintenance",
//     ],
//     category: "backend",
//     icon: Cpu,
//     gradient: "from-teal-500/10 to-blue-500/10",
//     featured: false,
//     duration: "9 months",
//     teamSize: "8 developers",
//   },
//   {
//     id: "ecommerce",
//     title: "Modern E-Commerce Platform",
//     description:
//       "Full-featured e-commerce solution with admin dashboard, payment integration, and inventory management.",
//     tech: [
//       "Next.js 14",
//       "TypeScript",
//       "Node.js",
//       "MongoDB",
//       "Stripe",
//       "Cloudinary",
//       "Tailwind CSS",
//     ],
//     status: "Completed",
//     github: "https://github.com/sorujmahmud/ecommerce-app",
//     demo: "https://ecommerce-soruj.vercel.app",
//     features: [
//       "Payment Processing",
//       "Admin Dashboard",
//       "Inventory Management",
//       "Responsive Design",
//     ],
//     category: "fullstack",
//     icon: ShoppingCart,
//     gradient: "from-yellow-500/10 to-orange-500/10",
//     featured: true,
//     duration: "3 months",
//     teamSize: "Solo",
//   },
//   {
//     id: "chat-app",
//     title: "Real-time Chat Application",
//     description:
//       "Real-time messaging application with rooms, file sharing, and live notifications.",
//     tech: [
//       "React",
//       "TypeScript",
//       "Socket.io",
//       "Node.js",
//       "MongoDB",
//       "Redis",
//       "Cloudinary",
//     ],
//     status: "Completed",
//     github: "https://github.com/sorujmahmud/chat-app",
//     demo: "https://chat-soruj.vercel.app",
//     features: [
//       "Real-time Messaging",
//       "File Sharing",
//       "Multiple Rooms",
//       "Push Notifications",
//     ],
//     category: "fullstack",
//     icon: ChartArea,
//     gradient: "from-cyan-500/10 to-blue-500/10",
//     featured: true,
//     duration: "2 months",
//     teamSize: "Solo",
//   },
//   {
//     id: "portfolio",
//     title: "Personal Portfolio Website",
//     description:
//       "Modern, responsive portfolio website with project showcase, blog, and contact integration.",
//     tech: [
//       "Next.js 14",
//       "TypeScript",
//       "Tailwind CSS",
//       "Framer Motion",
//       "MongoDB",
//       "NextAuth",
//     ],
//     status: "Completed",
//     github: "https://github.com/sorujmahmud/portfolio",
//     demo: "https://sorujmahmud.vercel.app",
//     features: [
//       "Responsive Design",
//       "Smooth Animations",
//       "SEO Optimized",
//       "Performance Focused",
//     ],
//     category: "frontend",
//     icon: Globe,
//     gradient: "from-pink-500/10 to-rose-500/10",
//     featured: true,
//     duration: "1 month",
//     teamSize: "Solo",
//   },
//   {
//     id: "task-manager",
//     title: "Advanced Task Management System",
//     description:
//       "Productivity application with task management, team collaboration, and time tracking features.",
//     tech: [
//       "React",
//       "Redux Toolkit",
//       "TypeScript",
//       "Node.js",
//       "PostgreSQL",
//       "Socket.io",
//       "React DnD",
//     ],
//     status: "Completed",
//     github: "https://github.com/sorujmahmud/task-manager",
//     demo: "https://taskmanager-soruj.vercel.app",
//     features: [
//       "Task Management",
//       "Team Collaboration",
//       "Time Tracking",
//       "Drag & Drop",
//     ],
//     category: "fullstack",
//     icon: CheckCircle,
//     gradient: "from-green-500/10 to-emerald-500/10",
//     featured: false,
//     duration: "4 months",
//     teamSize: "2 developers",
//   },
//   {
//     id: "weather-app",
//     title: "Weather Forecast Application",
//     description:
//       "Beautiful weather application with detailed forecasts, maps, and severe weather alerts.",
//     tech: [
//       "React",
//       "TypeScript",
//       "OpenWeather API",
//       "Mapbox GL JS",
//       "PWA",
//       "Service Workers",
//     ],
//     status: "Completed",
//     github: "https://github.com/sorujmahmud/weather-app",
//     demo: "https://weather-soruj.vercel.app",
//     features: [
//       "Weather Forecasts",
//       "Interactive Maps",
//       "PWA Support",
//       "Offline Functionality",
//     ],
//     category: "frontend",
//     icon: Cloud,
//     gradient: "from-sky-500/10 to-blue-500/10",
//     featured: false,
//     duration: "1.5 months",
//     teamSize: "Solo",
//   },
// ];

// Category filters
// export const categories = [
//   {
//     id: "all",
//     name: "All Projects",
//     icon: PinIcon,
//     count: allProjects.length,
//   },
//   {
//     id: "ai",
//     name: "AI/ML",
//     icon: Brain,
//     count: allProjects.filter((p) => p.category === "ai").length,
//   },
//   {
//     id: "fullstack",
//     name: "Full Stack",
//     icon: Wrench,
//     count: allProjects.filter((p) => p.category === "fullstack").length,
//   },
//   {
//     id: "frontend",
//     name: "Frontend",
//     icon: Globe,
//     count: allProjects.filter((p) => p.category === "frontend").length,
//   },
//   {
//     id: "mobile",
//     name: "Mobile",
//     icon: Phone,
//     count: allProjects.filter((p) => p.category === "mobile").length,
//   },
//   {
//     id: "backend",
//     name: "Backend",
//     icon: Database,
//     count: allProjects.filter((p) => p.category === "backend").length,
//   },
// ];


 // AI-focused skills with LangChain & MCP
  export const skills = [
    {
      category: "AI & Machine Learning",
      icon: Brain,
      technologies: [
        {
          name: "LangChain",
          level: 75,
          status: "actively-learning",
          description: "Building AI applications with LLM orchestration",
        },
        {
          name: "MCP",
          level: 65,
          status: "actively-learning",
          description: "Model Context Protocol for AI agents",
        },
        {
          name: "OpenAI API",
          level: 80,
          status: "comfortable",
          description: "Integrating AI models into applications",
        },
        {
          name: "Python",
          level: 70,
          status: "learning",
          description: "AI development and scripting",
        },
        {
          name: "Vector Databases",
          level: 60,
          status: "exploring",
          description: "Storing and querying AI embeddings",
        },
        {
          name: "AI Agents",
          level: 65,
          status: "learning",
          description: "Building autonomous AI systems",
        },
      ],
      description:
        "Building intelligent applications with AI orchestration and machine learning models",
      color: "purple",
      gradient: "from-purple-500 to-pink-500",
    },
    {
      category: "Frontend Development",
      icon: Code,
      technologies: [
        { name: "React", level: 85, status: "comfortable" },
        { name: "Next.js", level: 80, status: "comfortable" },
        { name: "TypeScript", level: 75, status: "learning" },
        { name: "Tailwind CSS", level: 90, status: "comfortable" },
        { name: "HTML/CSS", level: 95, status: "confident" },
        { name: "JavaScript", level: 88, status: "comfortable" },
      ],
      description:
        "Building responsive and interactive user interfaces with modern frameworks",
      color: "blue",
      gradient: "from-blue-500 to-cyan-500",
    },
    {
      category: "Backend Development",
      icon: Server ,
      technologies: [
        { name: "Node.js", level: 78, status: "learning" },
        { name: "Express", level: 75, status: "learning" },
        { name: "MongoDB", level: 70, status: "learning" },
        { name: "REST APIs", level: 80, status: "comfortable" },
        { name: "Python", level: 65, status: "exploring" },
        { name: "Firebase", level: 75, status: "comfortable" },
      ],
      description: "Learning server-side development and database management",
      color: "green",
      gradient: "from-green-500 to-emerald-500",
    },
    {
      category: "Tools & Technologies",
      icon: Workflow,
      technologies: [
        { name: "Git", level: 85, status: "comfortable" },
        { name: "VS Code", level: 90, status: "confident" },
        { name: "Docker", level: 50, status: "exploring" },
        { name: "Vercel", level: 80, status: "comfortable" },
        { name: "Figma", level: 70, status: "learning" },
        { name: "Postman", level: 85, status: "comfortable" },
      ],
      description: "Development tools and workflow optimization",
      color: "orange",
      gradient: "from-orange-500 to-red-500",
    },
  ];

  // Learning Journey - AI Focused
 export const learningJourney = [
    {
      phase: "Foundation Building",
      period: "2022 - 2023",
      focus: "Web Development Fundamentals",
      achievements: [
        "Mastered HTML, CSS, and JavaScript",
        "Built 20+ practice projects",
        "Learned React and modern frontend",
        "Completed online courses and bootcamps",
      ],
      icon: BookOpen,
      status: "completed",
    },
    {
      phase: "Full-Stack Development",
      period: "2023 - 2024",
      focus: "MERN Stack & Beyond",
      achievements: [
        "Built full-stack applications",
        "Learned backend with Node.js",
        "Mastered database management",
        "Deployed production projects",
      ],
      icon: Code,
      status: "completed",
    },
    {
      phase: "AI Specialization",
      period: "2024 - Present",
      focus: "LangChain & MCP Mastery",
      achievements: [
        "Learning LangChain for AI orchestration",
        "Exploring MCP for AI agents",
        "Building AI-powered applications",
        "Studying vector databases and embeddings",
      ],
      icon: Brain,
      status: "current",
    },
    {
      phase: "Career Launch",
      period: "Future",
      focus: "Professional AI Developer",
      achievements: [
        "Seeking junior AI developer roles",
        "Contributing to AI open-source",
        "Building production AI systems",
        "Continuous learning and growth",
      ],
      icon: Rocket,
      status: "upcoming",
    },
  ];

  // Personal Projects - AI Focused
//  export const projects = [
//     {
//       name: "LangChain Chat Assistant",
//       description:
//         "An intelligent chat application using LangChain for conversation memory and AI-powered responses",
//       tech: ["LangChain", "Next.js", "OpenAI API", "Vector DB"],
//       status: "In Progress",
//       type: "AI Application",
//       github: "#",
//       demo: "#",
//     },
//     {
//       name: "MCP Tools Explorer",
//       description:
//         "A project to understand and implement Model Context Protocol for AI agent tool usage",
//       tech: ["MCP", "TypeScript", "AI Agents"],
//       status: "Learning Phase",
//       type: "AI Research",
//       github: "#",
//       demo: "#",
//     },
//     {
//       name: "AI-Powered Portfolio",
//       description:
//         "Personal portfolio with AI integration showcasing modern development skills",
//       tech: ["Next.js", "LangChain", "Tailwind CSS"],
//       status: "Completed",
//       type: "Full-Stack",
//       github: "#",
//       demo: "#",
//     },
//   ];

 export const stats = [
    {
      number: "25+",
      label: "Projects Built",
      icon: Rocket,
      description: "Hands-on learning",
    },
    {
      number: "100%",
      label: "Learning Focus",
      icon: Brain,
      description: "AI specialization",
    },
    {
      number: "2+",
      label: "Years Learning",
      icon: Calendar ,
      description: "Continuous growth",
    },
    {
      number: "15+",
      label: "Technologies",
      icon: Cpu,
      description: "Diverse skillset",
    },
  ];
